baseURL = "http://example.org/"
languageCode = "en-us"
title = "works in fm"
theme = "hugo_theme_pickles"

[params]
  paginate = 10


[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4


